# <font color="blue">numpy</font>
- <h3>stands for numerical python.
-  it provide n dimensional homogenous mutable arrays. 
    </h3>

# Functions
- <h3>.array()  -  accepts a list and convert it into numpy array
- .ndim     - tells dimension of the array
- .shape    - tells the shape i.e no of subarrays/columns and no of elements/rows in the               subarray.
- .dtype    - tells the datatype of the array.(array must be homogeneous)
- .size     - tells total no of elements in a nd array. if shape = (x,y) then size = x* y
</h3>

In [3]:
import numpy as np

In [132]:
list1 = [1,2,3,4,5,6,7,8,9,10,11,12]
list2 = [[1,2],[3,4],[5,6]]
list3 = [[1,2,3],[4,5,6],[7,8]]

arr = np.array(list1)
arr2 = np.array(list2)
arr3 = np.array(list3)

print("arr = ",arr)
print("ndim = ",arr.ndim)
print("shape = ",arr.shape)   
print("dtype = ",arr.dtype)
print("size = ",arr.size)

print()

print("arr = ",arr2)
print("ndim = ",arr2.ndim)
print("shape = ",arr2.shape)   
print("size = ",arr2.size)

print()

print("arr = ",arr3)
print("ndim = ",arr3.ndim,"is not correct")    # gives ans = 1 but arr3 is 2d. this is becoz no of
                              # elements in each subarray is not equal.
    
print("shape = ",arr3.shape,"is not correct")  # this also gives the no of subarrays i.e 3 but not len of
                              # subarrays as all len of subarrays is not same.(3,)
    
print("size = ",arr3.size,"is not correct")    # as shape is (3,) then size is 3 which must be 8.

arr =  [ 1  2  3  4  5  6  7  8  9 10 11 12]
ndim =  1
shape =  (12,)
dtype =  int32
size =  12

arr =  [[1 2]
 [3 4]
 [5 6]]
ndim =  2
shape =  (3, 2)
size =  6

arr =  [list([1, 2, 3]) list([4, 5, 6]) list([7, 8])]
ndim =  1 is not correct
shape =  (3,) is not correct
size =  3 is not correct


# <font color="blue">.reshape(x,y)</font>
- <h3>to reshape a (m,n) dimensional array into a (x,y) dimensional array. but the condition m* n =  x* y must be satisfied.
- it doesn't change the shape of current array but returns a new array.</h3>

In [45]:
print(arr)
print(arr.shape)

arr2 = arr.reshape(2,6)   # it is valid as 2*6 = 12 which is size of arr.
print("new shape of array of 12 elements is : \n",arr2)

arr2 = arr.reshape(3,4)   # valid as 3*4 = 12
print("\narr in (3,4) shape\n",arr2)

arr2 = arr.reshape(6,2)
print("\narr in (6,2) shape\n",arr2)

arr2 = arr.reshape(12,1)
print("\narr in (12,1) shape\n",arr2)

#arr2 = arr.reshape(4,2)  # invalid statement as 4*2 != 12

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
new shape of array of 12 elements is : 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

arr in (3,4) shape
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

arr in (6,2) shape
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

arr in (12,1) shape
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


# <font color="blue">.flatten() and ravel() </font>
- <h3>.flatten() - it converts a 2d,3d,... array into 1 dimensional array. Return a new array
- .ravel()   - it also converts a array into 1d array. Returns a new array.</h3>

In [65]:
arr2 = arr.reshape(3,4)
print("\ncurrent array shape is \n",arr2)
arr2 = arr2.flatten()
print("\narray after flatten() is\n",arr2)

arr2 = arr.reshape(6,2)
print("\ncurrent array shape is \n",arr2)
arr2 = arr2.ravel()
print("\narray after ravel() is\n",arr2)


current array shape is 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

array after flatten() is
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

current array shape is 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

array after ravel() is
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


# <font color="blue">arange(start,end,step,dtype)</font>
- <h3>generates a series from start to end having equal spaced between them</h3>

In [133]:
arr = np.arange(10)       # from 0 to 10 excluding 10
print(arr,"\n")

arr = np.arange(2,78,4)  # from 2 till 78 in step of 4 excluding 78
print(arr,"\n")

arr = np.arange(20).reshape(5,4)  # creating a array of 20 elements in 5*4 shape
print(arr,"\n")

arr = np.arange(1.1,10.1)
print(arr,"\n")

arr = np.arange(2,20,2,float)     # creating a array of specific data type
print(arr,"\n")

#arr = np.arange('a','z')         # arange only works with numbers not strings.

arr = np.arange(1,50,5,complex)
print(arr,"\n")

arr = np.arange(1,50,5)
print(arr.dtype,"\n")

arr = np.arange(1,50,5,float)
print(arr.dtype,"\n")

arr = np.arange(1,50,5,list)
print(arr.dtype,"\n")

[0 1 2 3 4 5 6 7 8 9] 

[ 2  6 10 14 18 22 26 30 34 38 42 46 50 54 58 62 66 70 74] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]] 

[1.1 2.1 3.1 4.1 5.1 6.1 7.1 8.1 9.1] 

[ 2.  4.  6.  8. 10. 12. 14. 16. 18.] 

[ 1.+0.j  6.+0.j 11.+0.j 16.+0.j 21.+0.j 26.+0.j 31.+0.j 36.+0.j 41.+0.j
 46.+0.j] 

int32 

float64 

object 



# <font color="blue">ones, zeros, full, empty</font>
- <h3>creating arrays with values intialized with one,zero, other value or empty
- <font color ="brown">np.ones(shape, dtype=None, order='C')
- np.zeros(shape, dtype=None, order='C')
- np.empty(shape, dtype=None, order='C')
- np.full(shape, fill_value, dtype=None, order='C')
</font></h3>

In [189]:
arr = np.ones(10)   # create a arrays of size 10 initialzed with 1.
print(arr,"\n")
arr = np.zeros(10)  # create a arrays of size 10 initialzed with 0.
print(arr,"\n")

arr = np.empty(10)  # return an uninitialized array.
print(arr,"\n")

arr = np.full(10,6) # create a array of 10 elements initialized with 6.
print(arr,"\n")

#----------------------------2D-------------------------------------------

arr = np.zeros((2,3),int)  # creates a 2*3 array initailized with integer 0
print(arr,"\n")

arr = np.ones((4,5), dtype=int)
print(arr,"\n")

arr = np.full((1,10),34)  # creates a 1*10 array means create a array consisting of 1 
                          # subarray having 10 elements in it.
print(arr,"\n")

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[6 6 6 6 6 6 6 6 6 6] 

[[0 0 0]
 [0 0 0]] 

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]] 

[[34 34 34 34 34 34 34 34 34 34]] 



# linspace(strt, end, values,dtype=)
- <h3>returns x sequntial values between start and end .
- example linspace(0,5,10) --> it retuns 10 seqential values between 0 and 5
 </h3>

In [201]:
arr = np.linspace(0,5,10)
print(arr,"\n")

arr = np.linspace(1,10,5)
print(arr,"\n")
arr = np.linspace(1,10,5, dtype=int)
print(arr,"\n")

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ] 

[ 1.    3.25  5.5   7.75 10.  ] 

[ 1  3  5  7 10] 



# numpy.random  in python


In [81]:
arr = np.random.random(10)        # generates 10 random no between 0 and 1.
print(arr,"\n")

arr = np.random.random((4,5))     # generate 4*5 array of random no between 0 and 1.
print(arr,"\n")


[0.97768072 0.98710295 0.40407777 0.70738596 0.84780503 0.99797918
 0.94464723 0.20769367 0.43581099 0.37594573] 

[[0.83209725 0.46149435 0.79387035 0.36146272 0.32193389]
 [0.21314526 0.23853079 0.96923053 0.84950568 0.52906535]
 [0.39661165 0.70350997 0.0119952  0.87710662 0.29314025]
 [0.83344958 0.80607833 0.21583147 0.04796225 0.93758929]] 



# Array Slicing

In [241]:
arr = np.array([[-1, 2, 0, 4], 
                [4, -0.5, 6, 0], 
                [2.6, 0, 7, 8], 
                [3, -7, 4, 2.0]]) 

print(arr[:],"\n")    # print from starting index to the end
print(arr[2:],"\n")   # print from 2nd index to the end
print(arr[:3],"\n")   # print from starting index to the 2nd index excluding 3

# -------------------accessing indexes of the subarrays-----------------

print(arr[:,:2])   # access from starting to end index of the array and then 
                   # access from starting to 1st index of each subarray.
    
print(arr[:,::3])  # access only first and last index of each subarray in d whole array.

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]] 

[[ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]] 

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]] 

[[-1.   2. ]
 [ 4.  -0.5]
 [ 2.6  0. ]
 [ 3.  -7. ]]
[[-1.   4. ]
 [ 4.   0. ]
 [ 2.6  8. ]
 [ 3.   2. ]]


# integer Array indexing

In [246]:
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]] 
# here arr[[0]] is the indexes of rows and arr[[1]] is indexes of columns.
# it is equivalent to temp1
temp1 = np.array( [arr[0][3], arr[1][2], arr[2][1],arr[3][0]] )

print(temp)
print(temp1)

[4. 6. 0. 3.]
[4. 6. 0. 3.]


# boolean array indexing

In [274]:
arr = np.arange(3,60,6)
print(arr,"\n")
cond = (arr % 9 ==0)     # creates a boolean array with True if condtion
                         # satisfy on that particular index else Flase.
print(cond,"\n")

print(arr[cond])        # prints only those values which satisfy the condtion.

[ 3  9 15 21 27 33 39 45 51 57] 

[False  True False False  True False False  True False False] 

[ 9 27 45]


# Matrix opertions on the array


In [288]:
arr = np.arange(1,16).reshape(3,5)
print(arr,"\n")

print("\nadding 1 to arr:\n",arr+1)
print("\nsubtracting 1 from arr:\n",arr-1)
print("\nmultiplying 4 to arr:\n",arr*4)
print("\ndividing arr by 2\n",arr/2)

print("\ntransposing the arr:\n",arr.T)         # matrix transpose

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 


adding 1 to arr:
 [[ 2  3  4  5  6]
 [ 7  8  9 10 11]
 [12 13 14 15 16]]

subtracting 1 from arr:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

multiplying 4 to arr:
 [[ 4  8 12 16 20]
 [24 28 32 36 40]
 [44 48 52 56 60]]

dividing arr by 2
 [[0.5 1.  1.5 2.  2.5]
 [3.  3.5 4.  4.5 5. ]
 [5.5 6.  6.5 7.  7.5]]

transposing the arr:
 [[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [7]:
m1 = np.arange(1,16).reshape(3,5)
print("matrix 1 is \n",m1)

m2 = np.arange(1,16).reshape(3,5)
print("\nmatrix 2 is \n",m2)

print("\nelementwise addig both matrix: \n",m1+m2)        # this is elementwise adding
print("\nelementwise subtracting both matrix: \n",m1-m2)  # elementwise subtracting

print("\nelementwise multiplying both matrix: \n",m1*m2)  # element wise multiplication 
                                               # this is not a matrix multiplication.

print("\nreshaping m2 to make suitable for matrix multiplication")
m2=m2.reshape(5,3)
print(m2)

print("\nmatrix multiplication m1*m2 is : \n",m1.dot(m2))

matrix 1 is 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

matrix 2 is 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

elementwise addig both matrix: 
 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]

elementwise subtracting both matrix: 
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

elementwise multiplying both matrix: 
 [[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]]

reshaping m2 to make suitable for matrix multiplication
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

matrix multiplication m1*m2 is : 
 [[135 150 165]
 [310 350 390]
 [485 550 615]]


# sorting numpy array
- np.sort(a, axis=-1, kind=None, order=None)
    - a = array to be sorted
    - axis
        - -1  - 
        -  0  - column wise
        -  1  - row wise
        - None - if none then array is flattened before sorting.
    - kind  = {'quicksort', 'mergesort', 'heapsort', 'stable'} by default quciksort.

In [51]:
import random
list1 = list(range(1,16))
random.shuffle(list1)           # creating a shuffled list

arr = np.array(list1).reshape(3,5)
print("the array is:\n",arr,"\n")

print("sorting row wise by default:")
print(np.sort(arr),"\n")                    # sorting row wise (by default)

print("sorting column wise by default:")
print(np.sort(arr,axis=0),"\n")             # sorting columnwise

print("sorting array in 1d array:")
print(np.sort(arr,axis=None),"\n")  

print("sorting columnwise with mergersort:")
print(np.sort(arr,axis=0,kind='mergesort'),"\n")

the array is:
 [[ 2  6  1 13  3]
 [ 8  5  7 10 11]
 [14  4  9 15 12]] 

sorting row wise by default:
[[ 1  2  3  6 13]
 [ 5  7  8 10 11]
 [ 4  9 12 14 15]] 

sorting column wise by default:
[[ 2  4  1 10  3]
 [ 8  5  7 13 11]
 [14  6  9 15 12]] 

sorting array in 1d array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] 

sorting columnwise with mergersort:
[[ 2  4  1 10  3]
 [ 8  5  7 13 11]
 [14  6  9 15 12]] 



# creating custom data type in python

In [79]:
my_dtype = [("name","S20"),("rollno",int),("city","S15")]

# values must be in same order as data type is.
values = [
            ("shailesh",123,"DDN"),("shailesh",1213,"AGRA"),
              ("ankit",21,"HAR"),("Shubham",31,"DDL")
        ]

arr = np.array(values, dtype = my_dtype)
print(arr)

[(b'shailesh',  123, b'DDN') (b'shailesh', 1213, b'AGRA')
 (b'ankit',   21, b'HAR') (b'Shubham',   31, b'DDL')]


# sorting based on custom dtype

In [80]:
print("array with custom dtype: \n",arr)

print("\nsorting based on name:")
print(np.sort(arr, order = 'name'))   # case sensisitive as 'S' <'a','s'

print("\nsorting based on rollno:")
print(np.sort(arr, order = 'rollno'))

print("\nsorting based on city:")
print(np.sort(arr, order = 'city'))

print("\nsorting based on name and then city:")
print(np.sort(arr, order = ['name','city']))

array with custom dtype: 
 [(b'shailesh',  123, b'DDN') (b'shailesh', 1213, b'AGRA')
 (b'ankit',   21, b'HAR') (b'Shubham',   31, b'DDL')]

sorting based on name:
[(b'Shubham',   31, b'DDL') (b'ankit',   21, b'HAR')
 (b'shailesh',  123, b'DDN') (b'shailesh', 1213, b'AGRA')]

sorting based on rollno:
[(b'ankit',   21, b'HAR') (b'Shubham',   31, b'DDL')
 (b'shailesh',  123, b'DDN') (b'shailesh', 1213, b'AGRA')]

sorting based on city:
[(b'shailesh', 1213, b'AGRA') (b'Shubham',   31, b'DDL')
 (b'shailesh',  123, b'DDN') (b'ankit',   21, b'HAR')]

sorting based on name and then city:
[(b'Shubham',   31, b'DDL') (b'ankit',   21, b'HAR')
 (b'shailesh', 1213, b'AGRA') (b'shailesh',  123, b'DDN')]
